<a href="https://colab.research.google.com/github/MithileshBurra/NLP-Bow-TFIDF-/blob/main/BOW_%26_TF_IDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import re
import pandas as pd
import numpy as np

In [58]:
messages = pd.read_csv('/content/SMSspam.csv', encoding = 'latin-1')

In [59]:
messages = messages[['v1','v2']]

In [60]:
messages.columns = [['label','message']]

In [61]:
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [62]:
messages.columns = [col[0] for col in messages.columns]
print(messages.columns)

Index(['label', 'message'], dtype='object')


In [63]:
from nltk.stem import SnowballStemmer

In [64]:
ss = SnowballStemmer('english')

In [65]:
import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [76]:
corpus = []
for i in range(len(messages)):
  review = re.sub('[^A-Za-z]',' ',messages['message'].iloc[i])
  review = review.lower()
  review = review.split()

  review = [ss.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)


In [77]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkts st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breath

# BAG OF WORDS

In [78]:
y = pd.get_dummies(messages['label'])
y = y.iloc[:,0].values

In [79]:
y

array([ True,  True, False,  True,  True, False,  True,  True, False, False,  True, False, False,  True,  True, False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True,  True,  True,  True])

In [101]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(corpus,y,test_size = 0.2)

In [86]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500, ngram_range=(1,2))


In [104]:
type(X_test)

numpy.ndarray

In [103]:
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()

In [107]:
np.printoptions(edgeitems = 30, linewidth = 10000,
                formatter = dict(float = lambda x: ".3g" % x))
X_train


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [108]:
cv.vocabulary_

{'movi': np.int64(1350),
 'laptop': np.int64(1095),
 'urgent': np.int64(2264),
 'nd': np.int64(1385),
 'attempt': np.int64(112),
 'contact': np.int64(409),
 'call': np.int64(249),
 'wc': np.int64(2351),
 'xx': np.int64(2458),
 'ppm': np.int64(1615),
 'max': np.int64(1257),
 'urgent nd': np.int64(2267),
 'nd attempt': np.int64(1386),
 'attempt contact': np.int64(113),
 'contact call': np.int64(410),
 'wc xx': np.int64(2352),
 'think': np.int64(2097),
 'far': np.int64(675),
 'find': np.int64(699),
 'check': np.int64(335),
 'googl': np.int64(849),
 'map': np.int64(1243),
 'place': np.int64(1568),
 'sleep': np.int64(1890),
 'go': np.int64(810),
 'take': np.int64(2041),
 'haha': np.int64(895),
 'got': np.int64(850),
 'wat': np.int64(2339),
 'onlin': np.int64(1490),
 'repli': np.int64(1719),
 'mail': np.int64(1228),
 'lor': np.int64(1185),
 'what': np.int64(2377),
 'hous': np.int64(971),
 'beer': np.int64(160),
 'pick': np.int64(1559),
 'ur': np.int64(2240),
 'fone': np.int64(718),
 'dont': 

In [109]:
from sklearn.naive_bayes import MultinomialNB


In [110]:
model = MultinomialNB()

In [111]:
model.fit(X_train,y_train)

MultinomialNB()

In [112]:
y_pred = model.predict(X_test)

In [113]:
from sklearn.metrics import accuracy_score, classification_report

In [115]:
print(f" Accuracy = {accuracy_score(y_test,y_pred)}\n")
print(f" Classification Report \n {classification_report(y_test,y_pred)}")

 Accuracy = 0.9874439461883409

 Classification Report 
               precision    recall  f1-score   support

       False       0.99      0.91      0.95       149
        True       0.99      1.00      0.99       966

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [116]:
X_train,X_test,y_train,y_test = train_test_split(corpus,y,test_size = 0.2)

In [117]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [118]:
tfidf = TfidfVectorizer(max_features= 2500,ngram_range=(1,2))

In [119]:
X_train = tfidf.fit_transform(X_train).toarray()
X_test = tfidf.transform(X_test).toarray()

In [121]:
np.printoptions(edgeitems = 30, linewidth = 10000,
                formatter = dict(float = lambda x: ".3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [120]:
model2 = MultinomialNB()

In [122]:
model2.fit(X_train,y_train)

MultinomialNB()

In [125]:
y_pred = model2.predict(X_test)

In [126]:
print(f" Accuracy = {accuracy_score(y_test,y_pred)}\n")
print(f" Classification Report \n {classification_report(y_test,y_pred)}")

 Accuracy = 0.967713004484305

 Classification Report 
               precision    recall  f1-score   support

       False       0.99      0.79      0.88       163
        True       0.96      1.00      0.98       952

    accuracy                           0.97      1115
   macro avg       0.98      0.89      0.93      1115
weighted avg       0.97      0.97      0.97      1115

